---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
spec:
  selector:
    matchLabels:
      app: web-qa
  template:
    metadata:
      labels:
        app: web-qa
    spec:
      volumes:
        - name: nfs-pvc-web-vol
          persistentVolumeClaim:
            claimName: nfs-pvc-web
      containers:
      - name: httpd-{{BUILD_NUMBER}}
        image: httpd:2.4.48-alpine3.14
        ports:
        - containerPort: 80
        volumeMounts:
          - name: nfs-pvc-web-vol
            mountPath: /usr/local/apache2/htdocs
---
apiVersion: v1
kind: Service
metadata:
  name: web-server-service-qa
spec:
  selector:
    app: web-qa
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
