#Namespace
#
apiVersion: v1
kind: Namespace
metadata:
  name: httpd-on-k8s
  labels:
    name: httpd-on-k8s
#Deployment
#
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: httpd-server
  name: httpd-server
  namespace: httpd-on-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: httpd-server
    spec:
      containers:
      - name: httpd
        image: httpd:2.4
        resources: {}
