apiVersion: v1
kind: Namespace
metadata:
  name: httpd-from-jenkins-on-k8s

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: httpd-server
  name: httpd-server
  namespace: httpd-from-jenkins-on-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: httpd-server
    spec:
      containers:
        - image: httpd:2.4
        name: httpd
        resources: {}
