apiVersion: v1
kind: Namespace
metadata:
  name: web-${GIT_BRANCH}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-${GIT_BRANCH}
  namespace: web-${GIT_BRANCH}
spec:
  selector:
    matchLabels:
      app: web-${GIT_BRANCH}
  template:
    metadata:
      labels:
        app: web-${GIT_BRANCH}
    spec:
      volumes:
        - name: nfs-dyn-100mi-vol
          persistentVolumeClaim:
            claimName: nfs-dyn-100mi-pvc
      containers:
      - name: httpd-${GIT_BRANCH}
        image: httpd:2.4.48-alpine3.14
        ports:
        - containerPort: 80
        volumeMounts:
          - name: nfs-dyn-100mi-vol
            mountPath: /usr/local/apache2/htdocs
---
apiVersion: v1
kind: Service
metadata:
  name: web-server-service-${GIT_BRANCH}
  namespace: web-${GIT_BRANCH}
spec:
  selector:
    app: web-${GIT_BRANCH}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

