apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-dyn-100mi-pv
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Mi
  nfs:
    path: /kubernetes-share
    server: nfs-for-kubernetes.lab.net
