def namespace = "web-${BRANCH_NAME}"
def pvc_name = "web-pvc-${BRANCH_NAME}"
def app_name  = "httpd-${BUILD_NUMBER}"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ pvc_name }}
  namespace: {{ namespace }}
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
