apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-dyn-100mi-pvc
  namespace: web
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
