apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-dyn-100mi-pvc-$env.BRANCH_NAME
  namespace: web-$env.BRANCH_NAME
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
